### ISSUE TITLE
Segfault when starting Autonity with no validators

### ISSUE THREAD

**Issue by yazzaoui** [clearmatics/autonity#339]
With a genesis file with no validators we have a panic. At the moment there is no requirement on the minimum number of validators. We can set it to 1 and it would work or to 4 for making sure that an Autonity network is resilient to at least one faulty node.

```yaml
default_genesis:
  config:
    homesteadBlock: 0
    eip150Block: 0
    eip150Hash: '0x0000000000000000000000000000000000000000000000000000000000000000'
    eip155Block: 0
    eip158Block: 0
    petersburgBlock: 0
    constantinopleBlock: 0
    byzantiumBlock: 0
    tendermint:
      policy: 0
      block-period: 1
    chainId: 9999
    autonityContract:
      deployer: '0x0000000000000000000000000000000000000002'
      bytecode: ''
      abi: ''
      minGasPrice: 10000000000000
      operator: '0xae223655126e514C9C80096d99765A98547247D3'
      users:
      - enode: enode://e1780e8136a6744b4cad3d8d56fed349b72fd5617bf1443c61cafb418f7efe844aa142ad44149d3a7aa1e7410f025e1bd0fafa320213f43a0306a062f9275dc1@127.0.0.1:30302
        type: participant
  nonce: '0x0'
  timestamp: '0x0'
  gasLimit: '0x5F5E100'
  difficulty: '0x1'
  coinbase: '0x0000000000000000000000000000000000000000'
  number: '0x0'
  gasUsed: '0x0'
  parentHash: '0x0000000000000000000000000000000000000000000000000000000000000000'
  mixHash: '0x63746963616c2062797a616e74696e65206661756c7420746f6c6572616e6365'
  alloc:
    0x981dfa463bE3c247Fe311a05EeD4c67265204417:
      balance: '0x200000000000000000000000000000000000000000000000000000000000000'
```

stack trace:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xc02cd0]

goroutine 119 [running]:
github.com/clearmatics/autonity/consensus/tendermint/validator.(*defaultSet).getProposer(...)
    /autonity/build/_workspace/src/github.com/clearmatics/autonity/consensus/tendermint/validator/default.go:139
github.com/clearmatics/autonity/consensus/tendermint/validator.(*defaultSet).IsProposer(0xc019686690, 0xd494c2a8ab5b48ae, 0x5aac105bf5ec705e, 0xfafee709, 0x0)
    /autonity/build/_workspace/src/github.com/clearmatics/autonity/consensus/tendermint/validator/default.go:147 +0xb0
github.com/clearmatics/autonity/consensus/tendermint/core.(*validatorSet).IsProposer(0xc00009b3b0, 0xd494c2a8ab5b48ae, 0x5aac105bf5ec705e, 0xc0fafee709, 0x0)
    /autonity/build/_workspace/src/github.com/clearmatics/autonity/consensus/tendermint/core/validator_set.go:109 +0x91
github.com/clearmatics/autonity/consensus/tendermint/core.(*core).isProposer(...)
    /autonity/build/_workspace/src/github.com/clearmatics/autonity/consensus/tendermint/core/core.go:223
github.com/clearmatics/autonity/consensus/tendermint/core.(*core).startRound(0xc0000ce280, 0x1410020, 0xc019fa6a00, 0xc0000a40c0)
    /autonity/build/_workspace/src/github.com/clearmatics/autonity/consensus/tendermint/core/core.go:281 +0x2f7
github.com/clearmatics/autonity/consensus/tendermint/core.(*core).handleConsensusEvents(0xc0000ce280, 0x1410020, 0xc019fa6a00)
    /autonity/build/_workspace/src/github.com/clearmatics/autonity/consensus/tendermint/core/handler.go:160 +0x69
created by github.com/clearmatics/autonity/consensus/tendermint/core.(*core).Start
```

Related:
- https://github.com/clearmatics/autonity/issues/308
